# Generated by Django 4.2.5 on 2023-09-23 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfarmer', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='customuser',
        ),
    ]
